base_cluster_path: "~/Testing/Clusters"
base_ocs_path: "~/Testing/OCS-CI"

# The Openshift cluster information
cluster_path: "{{ base_cluster_path }}/VC7-Arbiter"
cluster_name: "alayani-arbiter"
cluster_config_file: "{{ base_ocs_path }}/conf/avili/vc7_arbiter_conf.yaml"
kubeconfig: "{{ cluster_path }}/auth/kubeconfig"

# the default delay to inject for network truffic (one way)
inj_delay: 5

zone_locator: "topology.kubernetes.io/zone"
zones:
  zonea: "Zone-A"
  zoneb: "Zone-B"
  zonec: "Zone-C"
