---
- name: "Check oc and cluster access"
  hosts: "control"
  become: "false"
  tags:
    - checking
  tasks:
    - name: "Verify That OC client  is exist"
      command: 
        cmd: "which oc"
      register: rc
      failed_when: "rc.rc != 0"

    - name: "Verify that OCP is accessiable"
      shell:
        cmd: "oc get node --kubeconfig {{ kubeconfig }} >/dev/null 2>&1"
      register: rc
      failed_when: "rc.rc != 0"

- name: "Labeling nodes with zone name"
  include: zoning.yml
  tags:
    - labeling

- name: "Enableing Netem"
  hosts: "nodes"
  remote_user: "core"  
  tags:
    - setup
  tasks:

    - name: "Copy configuration script"
      template:
        src: "{{ playbook_dir }}/templates/tcrun.sh.j2"
        dest: "/tmp/tcrun.sh"
        mode: "0755"  

    - name: "Setting up latency on the nodes" 
      become: "true"
      command:
        cmd: "/tmp/tcrun.sh"

