---
- name: "Getting the netem bundle"
  hosts: "control"
  become: "false"
  tasks:
    - name: "Verify That OC client  is exist"
      command: 
        cmd: "which oc"
      register: rc
      failed_when: "rc.rc != 0"

    - name: "Verify that OCP is accessiable"
      shell:
        cmd: "oc get node --kubeconfig {{ kubeconfig }} >/dev/null 2>&1"
      register: rc
      failed_when: "rc.rc != 0"

    - name: "Getting the rpm file"
      get_url:
        url: "{{ netem_get_pkg }}"
        dest: "{{ playbook_dir }}/{{ netem_trg_pkg }}"
        mode: "0664"

- name: "Labeling nodes with zone name"
  hosts: nodes
  become: "false"
  gather_facts: "false"
  tasks:

    - name: "Check if node labeld with the zone name"
      shell:
        cmd: "oc get node --kubeconfig {{ kubeconfig }} -o json | grep  {{ zone_locator }} | grep {{ zones[hostvars[inventory_hostname].group_names[-1]] }}"
      register: rc
      delegate_to: localhost

    - name: "Labaleing the node"
      shell:
        cmd: "oc label {{ inventory_hostname }} {{ zone_locator }}={{ zones[hostvars[inventory_hostname].group_names[-1]] }}"
      delegate_to: localhost
      when: "rc.rc != 0"

- name: "Enableing Netem"
  hosts: "nodes"
  remote_user: "core"  
  tasks:
    - name: "Copy the Netem package to the hosts"
      copy:
        src: "{{ playbook_dir }}/{{ netem_trg_pkg }}"
        dest: "/tmp/"

    - name: "Copy configuration script"
      template:
        src: "{{ playbook_dir }}/templates/tcrun.sh.j2"
        dest: "/tmp/tcrun.sh"
        mode: "0755"  

    - name: "Setting up latency on the nodes" 
      become: "true"
      command:
        cmd: "/tmp/tcrun.sh"

